name: Build

runs:
    using: composite

    steps:
      - name: Create build directory
        run: mkdir build
        shell: bash

      - name: Configure
        run: |
          cmake -LA .. \
           -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
           -DBUILD_HEADERS=OFF \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
           -DPROTOZERO_INCLUDE_DIR=${GITHUB_WORKSPACE}/../protozero/include
        shell: bash
        working-directory: build

      - name: Build
        run: cmake --build .
        shell: bash
        working-directory: build

